CREATE OR REPLACE DIRECTORY WCCSD_DIR
AS 'C:\external';

SELECT * FROM ALL_DIRECTORIES
WHERE DIRECTORY_NAME='WCCSD_DIR';

CREATE TABLE WCCSD_PIPE(
OBJECTID VARCHAR(255),
FEATURE_ID VARCHAR(255),
FROM_MH VARCHAR(255),
LENGTH_FT VARCHAR(255),
DIAMETER VARCHAR(255),
MATERIAL VARCHAR(255),
SLOPE VARCHAR(255),
CFCC VARCHAR(255),
STORMWATER VARCHAR(255),
LANDUSE VARCHAR2(255),
PCI VARCHAR(255),
KNOWN_ISSUES VARCHAR2(255),
PACP VARCHAR2(255),
UPSOURCE VARCHAR2(255),
AGE VARCHAR(255),
FLOW_TO VARCHAR(255),
RISE VARCHAR(255),
SHAPE VARCHAR2(4000),
GDB_GEOMATTR_DATA VARCHAR(255),
UPSTREAM_CNT VARCHAR(255),
SL_CLASS VARCHAR(255),
Q_INF VARCHAR(255),
Q VARCHAR(255),
D_LEFT_TARGET VARCHAR(255),
DN VARCHAR(255),
N_FULL VARCHAR(255),
SED_VOL VARCHAR(255),
DIRECT_CNT VARCHAR(255),
FLUSH_PER_YEAR VARCHAR(255),
VEG_SCORE VARCHAR(255),
SED_PER_YR VARCHAR(255),
MH_ANGLE VARCHAR(255),
V VARCHAR(255))
ORGANIZATION EXTERNAL
  (TYPE ORACLE_LOADER
  DEFAULT DIRECTORY WCCSD_DIR
  ACCESS PARAMETERS
    (RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
    )
  LOCATION ('Sewer_Main_Variables.csv')
  )
  REJECT LIMIT UNLIMITED;
  DROP TABLE WCCSD_PIPE;
  SELECT * FROM WCCSD_PIPE;
  DESC WCCSD_PIPE;
  DELETE WCCSD_PIPE WHERE OBJECTID='OBJECTID';
  
CREATE TABLE USERS(
USER_ID NUMBER,
NAME VARCHAR2(100),
ADMIN CHAR DEFAULT 'N' NOT NULL);

ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY (USER_ID);
DESC USERS;
INSERT INTO USERS VALUES(1, 'ADMIN', DEFAULT);
INSERT INTO USERS VALUES(2, 'TECH1', 'N');
INSERT INTO USERS VALUES(3, 'TECH2', 'N');
SELECT * FROM USERS;
UPDATE USERS
SET ADMIN = 'Y'
WHERE USER_ID = 1;
SELECT * FROM USERS;

ALTER TABLE USERS
ADD PASSWORD VARCHAR2(100) DEFAULT 'PASSWORD';
